// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shortvid-service/v1/file.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileRequest) Reset() {
	*x = UploadFileRequest{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileRequest) ProtoMessage() {}

func (x *UploadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileRequest.ProtoReflect.Descriptor instead.
func (*UploadFileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{0}
}

type UploadFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadFileReply) Reset() {
	*x = UploadFileReply{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadFileReply) ProtoMessage() {}

func (x *UploadFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadFileReply.ProtoReflect.Descriptor instead.
func (*UploadFileReply) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{1}
}

type UpdateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileRequest) Reset() {
	*x = UpdateFileRequest{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileRequest) ProtoMessage() {}

func (x *UpdateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{2}
}

type UpdateFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileReply) Reset() {
	*x = UpdateFileReply{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileReply) ProtoMessage() {}

func (x *UpdateFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileReply.ProtoReflect.Descriptor instead.
func (*UpdateFileReply) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{3}
}

type DeleteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileRequest) Reset() {
	*x = DeleteFileRequest{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileRequest) ProtoMessage() {}

func (x *DeleteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileRequest.ProtoReflect.Descriptor instead.
func (*DeleteFileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{4}
}

type DeleteFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFileReply) Reset() {
	*x = DeleteFileReply{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFileReply) ProtoMessage() {}

func (x *DeleteFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFileReply.ProtoReflect.Descriptor instead.
func (*DeleteFileReply) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{5}
}

type GetFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileRequest) Reset() {
	*x = GetFileRequest{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileRequest) ProtoMessage() {}

func (x *GetFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileRequest.ProtoReflect.Descriptor instead.
func (*GetFileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{6}
}

type GetFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileReply) Reset() {
	*x = GetFileReply{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileReply) ProtoMessage() {}

func (x *GetFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileReply.ProtoReflect.Descriptor instead.
func (*GetFileReply) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{7}
}

type ListFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileRequest) Reset() {
	*x = ListFileRequest{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileRequest) ProtoMessage() {}

func (x *ListFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileRequest.ProtoReflect.Descriptor instead.
func (*ListFileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{8}
}

type ListFileReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFileReply) Reset() {
	*x = ListFileReply{}
	mi := &file_shortvid_service_v1_file_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFileReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFileReply) ProtoMessage() {}

func (x *ListFileReply) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_file_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFileReply.ProtoReflect.Descriptor instead.
func (*ListFileReply) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_file_proto_rawDescGZIP(), []int{9}
}

var File_shortvid_service_v1_file_proto protoreflect.FileDescriptor

const file_shortvid_service_v1_file_proto_rawDesc = "" +
	"\n" +
	"\x1eshortvid-service/v1/file.proto\x1a\x1cgoogle/api/annotations.proto\"\x13\n" +
	"\x11UploadFileRequest\"\x11\n" +
	"\x0fUploadFileReply\"\x13\n" +
	"\x11UpdateFileRequest\"\x11\n" +
	"\x0fUpdateFileReply\"\x13\n" +
	"\x11DeleteFileRequest\"\x11\n" +
	"\x0fDeleteFileReply\"\x10\n" +
	"\x0eGetFileRequest\"\x0e\n" +
	"\fGetFileReply\"\x11\n" +
	"\x0fListFileRequest\"\x0f\n" +
	"\rListFileReply2\xe7\x01\n" +
	"\x04File\x12R\n" +
	"\n" +
	"UploadFile\x12\x12.UploadFileRequest\x1a\x10.UploadFileReply\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/file/upload\x122\n" +
	"\n" +
	"DeleteFile\x12\x12.DeleteFileRequest\x1a\x10.DeleteFileReply\x12)\n" +
	"\aGetFile\x12\x0f.GetFileRequest\x1a\r.GetFileReply\x12,\n" +
	"\bListFile\x12\x10.ListFileRequest\x1a\x0e.ListFileReplyBH\n" +
	"\x17api.shortvid-service.v1P\x01Z+shortvid-backend/api/shortvid-service/v1;v1b\x06proto3"

var (
	file_shortvid_service_v1_file_proto_rawDescOnce sync.Once
	file_shortvid_service_v1_file_proto_rawDescData []byte
)

func file_shortvid_service_v1_file_proto_rawDescGZIP() []byte {
	file_shortvid_service_v1_file_proto_rawDescOnce.Do(func() {
		file_shortvid_service_v1_file_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_file_proto_rawDesc), len(file_shortvid_service_v1_file_proto_rawDesc)))
	})
	return file_shortvid_service_v1_file_proto_rawDescData
}

var file_shortvid_service_v1_file_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_shortvid_service_v1_file_proto_goTypes = []any{
	(*UploadFileRequest)(nil), // 0: UploadFileRequest
	(*UploadFileReply)(nil),   // 1: UploadFileReply
	(*UpdateFileRequest)(nil), // 2: UpdateFileRequest
	(*UpdateFileReply)(nil),   // 3: UpdateFileReply
	(*DeleteFileRequest)(nil), // 4: DeleteFileRequest
	(*DeleteFileReply)(nil),   // 5: DeleteFileReply
	(*GetFileRequest)(nil),    // 6: GetFileRequest
	(*GetFileReply)(nil),      // 7: GetFileReply
	(*ListFileRequest)(nil),   // 8: ListFileRequest
	(*ListFileReply)(nil),     // 9: ListFileReply
}
var file_shortvid_service_v1_file_proto_depIdxs = []int32{
	0, // 0: File.UploadFile:input_type -> UploadFileRequest
	4, // 1: File.DeleteFile:input_type -> DeleteFileRequest
	6, // 2: File.GetFile:input_type -> GetFileRequest
	8, // 3: File.ListFile:input_type -> ListFileRequest
	1, // 4: File.UploadFile:output_type -> UploadFileReply
	5, // 5: File.DeleteFile:output_type -> DeleteFileReply
	7, // 6: File.GetFile:output_type -> GetFileReply
	9, // 7: File.ListFile:output_type -> ListFileReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortvid_service_v1_file_proto_init() }
func file_shortvid_service_v1_file_proto_init() {
	if File_shortvid_service_v1_file_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_file_proto_rawDesc), len(file_shortvid_service_v1_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortvid_service_v1_file_proto_goTypes,
		DependencyIndexes: file_shortvid_service_v1_file_proto_depIdxs,
		MessageInfos:      file_shortvid_service_v1_file_proto_msgTypes,
	}.Build()
	File_shortvid_service_v1_file_proto = out.File
	file_shortvid_service_v1_file_proto_goTypes = nil
	file_shortvid_service_v1_file_proto_depIdxs = nil
}
