// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/shortvid-service/v1/upload.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetUploadPresignedURLReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUploadPresignedURLReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUploadPresignedURLReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUploadPresignedURLReplyMultiError, or nil if none found.
func (m *GetUploadPresignedURLReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUploadPresignedURLReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return GetUploadPresignedURLReplyMultiError(errors)
	}

	return nil
}

// GetUploadPresignedURLReplyMultiError is an error wrapping multiple
// validation errors returned by GetUploadPresignedURLReply.ValidateAll() if
// the designated constraints aren't met.
type GetUploadPresignedURLReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUploadPresignedURLReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUploadPresignedURLReplyMultiError) AllErrors() []error { return m }

// GetUploadPresignedURLReplyValidationError is the validation error returned
// by GetUploadPresignedURLReply.Validate if the designated constraints aren't met.
type GetUploadPresignedURLReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUploadPresignedURLReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUploadPresignedURLReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUploadPresignedURLReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUploadPresignedURLReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUploadPresignedURLReplyValidationError) ErrorName() string {
	return "GetUploadPresignedURLReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUploadPresignedURLReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUploadPresignedURLReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUploadPresignedURLReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUploadPresignedURLReplyValidationError{}

// Validate checks the field values on GetUploadSessionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetUploadSessionReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetUploadSessionReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetUploadSessionReplyMultiError, or nil if none found.
func (m *GetUploadSessionReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetUploadSessionReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessKeyId

	// no validation rules for SecretAccessKey

	// no validation rules for SessionToken

	if len(errors) > 0 {
		return GetUploadSessionReplyMultiError(errors)
	}

	return nil
}

// GetUploadSessionReplyMultiError is an error wrapping multiple validation
// errors returned by GetUploadSessionReply.ValidateAll() if the designated
// constraints aren't met.
type GetUploadSessionReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetUploadSessionReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetUploadSessionReplyMultiError) AllErrors() []error { return m }

// GetUploadSessionReplyValidationError is the validation error returned by
// GetUploadSessionReply.Validate if the designated constraints aren't met.
type GetUploadSessionReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetUploadSessionReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetUploadSessionReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetUploadSessionReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetUploadSessionReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetUploadSessionReplyValidationError) ErrorName() string {
	return "GetUploadSessionReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetUploadSessionReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetUploadSessionReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetUploadSessionReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetUploadSessionReplyValidationError{}

// Validate checks the field values on ListBucketsReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListBucketsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListBucketsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListBucketsReplyMultiError, or nil if none found.
func (m *ListBucketsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListBucketsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListBucketsReplyMultiError(errors)
	}

	return nil
}

// ListBucketsReplyMultiError is an error wrapping multiple validation errors
// returned by ListBucketsReply.ValidateAll() if the designated constraints
// aren't met.
type ListBucketsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListBucketsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListBucketsReplyMultiError) AllErrors() []error { return m }

// ListBucketsReplyValidationError is the validation error returned by
// ListBucketsReply.Validate if the designated constraints aren't met.
type ListBucketsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListBucketsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListBucketsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListBucketsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListBucketsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListBucketsReplyValidationError) ErrorName() string { return "ListBucketsReplyValidationError" }

// Error satisfies the builtin error interface
func (e ListBucketsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListBucketsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListBucketsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListBucketsReplyValidationError{}
