// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/shortvid-service/v1/upload.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUploadPresignedURLReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUploadPresignedURLReply) Reset() {
	*x = GetUploadPresignedURLReply{}
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadPresignedURLReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadPresignedURLReply) ProtoMessage() {}

func (x *GetUploadPresignedURLReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadPresignedURLReply.ProtoReflect.Descriptor instead.
func (*GetUploadPresignedURLReply) Descriptor() ([]byte, []int) {
	return file_api_shortvid_service_v1_upload_proto_rawDescGZIP(), []int{0}
}

func (x *GetUploadPresignedURLReply) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetUploadSessionReply struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessKeyId     string                 `protobuf:"bytes,1,opt,name=access_key_id,json=accessKeyId,proto3" json:"access_key_id,omitempty"`
	SecretAccessKey string                 `protobuf:"bytes,2,opt,name=secret_access_key,json=secretAccessKey,proto3" json:"secret_access_key,omitempty"`
	SessionToken    string                 `protobuf:"bytes,3,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUploadSessionReply) Reset() {
	*x = GetUploadSessionReply{}
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUploadSessionReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUploadSessionReply) ProtoMessage() {}

func (x *GetUploadSessionReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUploadSessionReply.ProtoReflect.Descriptor instead.
func (*GetUploadSessionReply) Descriptor() ([]byte, []int) {
	return file_api_shortvid_service_v1_upload_proto_rawDescGZIP(), []int{1}
}

func (x *GetUploadSessionReply) GetAccessKeyId() string {
	if x != nil {
		return x.AccessKeyId
	}
	return ""
}

func (x *GetUploadSessionReply) GetSecretAccessKey() string {
	if x != nil {
		return x.SecretAccessKey
	}
	return ""
}

func (x *GetUploadSessionReply) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ListBucketsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buckets       []string               `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBucketsReply) Reset() {
	*x = ListBucketsReply{}
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBucketsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBucketsReply) ProtoMessage() {}

func (x *ListBucketsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_shortvid_service_v1_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBucketsReply.ProtoReflect.Descriptor instead.
func (*ListBucketsReply) Descriptor() ([]byte, []int) {
	return file_api_shortvid_service_v1_upload_proto_rawDescGZIP(), []int{2}
}

func (x *ListBucketsReply) GetBuckets() []string {
	if x != nil {
		return x.Buckets
	}
	return nil
}

var File_api_shortvid_service_v1_upload_proto protoreflect.FileDescriptor

const file_api_shortvid_service_v1_upload_proto_rawDesc = "" +
	"\n" +
	"$api/shortvid-service/v1/upload.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x1aGetUploadPresignedURLReply\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8c\x01\n" +
	"\x15GetUploadSessionReply\x12\"\n" +
	"\raccess_key_id\x18\x01 \x01(\tR\vaccessKeyId\x12*\n" +
	"\x11secret_access_key\x18\x02 \x01(\tR\x0fsecretAccessKey\x12#\n" +
	"\rsession_token\x18\x03 \x01(\tR\fsessionToken\",\n" +
	"\x10ListBucketsReply\x12\x18\n" +
	"\abuckets\x18\x01 \x03(\tR\abuckets2\xca\x02\n" +
	"\rUploadService\x12u\n" +
	"\x15GetUploadPresignedURL\x12\x16.google.protobuf.Empty\x1a\x1b.GetUploadPresignedURLReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/v1/upload/presigned-url\x12e\n" +
	"\x10GetUploadSession\x12\x16.google.protobuf.Empty\x1a\x16.GetUploadSessionReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/upload/session\x12[\n" +
	"\vListBuckets\x12\x16.google.protobuf.Empty\x1a\x11.ListBucketsReply\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/upload/bucketsB-Z+shortvid-backend/api/shortvid-service/v1;v1b\x06proto3"

var (
	file_api_shortvid_service_v1_upload_proto_rawDescOnce sync.Once
	file_api_shortvid_service_v1_upload_proto_rawDescData []byte
)

func file_api_shortvid_service_v1_upload_proto_rawDescGZIP() []byte {
	file_api_shortvid_service_v1_upload_proto_rawDescOnce.Do(func() {
		file_api_shortvid_service_v1_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_shortvid_service_v1_upload_proto_rawDesc), len(file_api_shortvid_service_v1_upload_proto_rawDesc)))
	})
	return file_api_shortvid_service_v1_upload_proto_rawDescData
}

var file_api_shortvid_service_v1_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_shortvid_service_v1_upload_proto_goTypes = []any{
	(*GetUploadPresignedURLReply)(nil), // 0: GetUploadPresignedURLReply
	(*GetUploadSessionReply)(nil),      // 1: GetUploadSessionReply
	(*ListBucketsReply)(nil),           // 2: ListBucketsReply
	(*emptypb.Empty)(nil),              // 3: google.protobuf.Empty
}
var file_api_shortvid_service_v1_upload_proto_depIdxs = []int32{
	3, // 0: UploadService.GetUploadPresignedURL:input_type -> google.protobuf.Empty
	3, // 1: UploadService.GetUploadSession:input_type -> google.protobuf.Empty
	3, // 2: UploadService.ListBuckets:input_type -> google.protobuf.Empty
	0, // 3: UploadService.GetUploadPresignedURL:output_type -> GetUploadPresignedURLReply
	1, // 4: UploadService.GetUploadSession:output_type -> GetUploadSessionReply
	2, // 5: UploadService.ListBuckets:output_type -> ListBucketsReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_shortvid_service_v1_upload_proto_init() }
func file_api_shortvid_service_v1_upload_proto_init() {
	if File_api_shortvid_service_v1_upload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_shortvid_service_v1_upload_proto_rawDesc), len(file_api_shortvid_service_v1_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_shortvid_service_v1_upload_proto_goTypes,
		DependencyIndexes: file_api_shortvid_service_v1_upload_proto_depIdxs,
		MessageInfos:      file_api_shortvid_service_v1_upload_proto_msgTypes,
	}.Build()
	File_api_shortvid_service_v1_upload_proto = out.File
	file_api_shortvid_service_v1_upload_proto_goTypes = nil
	file_api_shortvid_service_v1_upload_proto_depIdxs = nil
}
