// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: shortvid-service/v1/upload.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUploadServiceGetUploadSession = "/UploadService/GetUploadSession"
const OperationUploadServiceListBuckets = "/UploadService/ListBuckets"

type UploadServiceHTTPServer interface {
	GetUploadSession(context.Context, *emptypb.Empty) (*GetUploadSessionReply, error)
	ListBuckets(context.Context, *emptypb.Empty) (*ListBucketsReply, error)
}

func RegisterUploadServiceHTTPServer(s *http.Server, srv UploadServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/upload/session", _UploadService_GetUploadSession0_HTTP_Handler(srv))
	r.POST("/api/v1/upload/buckets", _UploadService_ListBuckets0_HTTP_Handler(srv))
}

func _UploadService_GetUploadSession0_HTTP_Handler(srv UploadServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUploadServiceGetUploadSession)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUploadSession(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUploadSessionReply)
		return ctx.Result(200, reply)
	}
}

func _UploadService_ListBuckets0_HTTP_Handler(srv UploadServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUploadServiceListBuckets)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListBuckets(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListBucketsReply)
		return ctx.Result(200, reply)
	}
}

type UploadServiceHTTPClient interface {
	GetUploadSession(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *GetUploadSessionReply, err error)
	ListBuckets(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *ListBucketsReply, err error)
}

type UploadServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUploadServiceHTTPClient(client *http.Client) UploadServiceHTTPClient {
	return &UploadServiceHTTPClientImpl{client}
}

func (c *UploadServiceHTTPClientImpl) GetUploadSession(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*GetUploadSessionReply, error) {
	var out GetUploadSessionReply
	pattern := "/api/v1/upload/session"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUploadServiceGetUploadSession))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *UploadServiceHTTPClientImpl) ListBuckets(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*ListBucketsReply, error) {
	var out ListBucketsReply
	pattern := "/api/v1/upload/buckets"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUploadServiceListBuckets))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
