// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shortvid-service/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginFirebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=idToken,proto3" json:"idToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseRequest) Reset() {
	*x = LoginFirebaseRequest{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseRequest) ProtoMessage() {}

func (x *LoginFirebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseRequest.ProtoReflect.Descriptor instead.
func (*LoginFirebaseRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginFirebaseRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type LoginFirebaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	User          *UserProfile           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseResponse) Reset() {
	*x = LoginFirebaseResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseResponse) ProtoMessage() {}

func (x *LoginFirebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseResponse.ProtoReflect.Descriptor instead.
func (*LoginFirebaseResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginFirebaseResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginFirebaseResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginFirebaseResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserUid       int32                  `protobuf:"varint,2,opt,name=userUid,proto3" json:"userUid,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,6,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUid   string                 `protobuf:"bytes,7,opt,name=providerUid,proto3" json:"providerUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserProfile) GetUserUid() int32 {
	if x != nil {
		return x.UserUid
	}
	return 0
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UserProfile) GetProviderUid() string {
	if x != nil {
		return x.ProviderUid
	}
	return ""
}

type GetUserProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUid       int32                  `protobuf:"varint,1,opt,name=userUid,proto3" json:"userUid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileRequest) Reset() {
	*x = GetUserProfileRequest{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileRequest) ProtoMessage() {}

func (x *GetUserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileRequest.ProtoReflect.Descriptor instead.
func (*GetUserProfileRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserProfileRequest) GetUserUid() int32 {
	if x != nil {
		return x.UserUid
	}
	return 0
}

type GetUserProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserProfile           `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserProfileResponse) Reset() {
	*x = GetUserProfileResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserProfileResponse) ProtoMessage() {}

func (x *GetUserProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserProfileResponse.ProtoReflect.Descriptor instead.
func (*GetUserProfileResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserProfileResponse) GetUserInfo() *UserProfile {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserProfile           `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoResponse) Reset() {
	*x = UserInfoResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoResponse) ProtoMessage() {}

func (x *UserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoResponse.ProtoReflect.Descriptor instead.
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfoResponse) GetUserInfo() *UserProfile {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_shortvid_service_v1_user_proto protoreflect.FileDescriptor

const file_shortvid_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1eshortvid-service/v1/user.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x14LoginFirebaseRequest\x12\x18\n" +
	"\aidToken\x18\x01 \x01(\tR\aidToken\"\x7f\n" +
	"\x15LoginFirebaseResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.UserProfileR\x04user\"\xbf\x01\n" +
	"\vUserProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x18\n" +
	"\auserUid\x18\x02 \x01(\x05R\auserUid\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x06 \x01(\tR\bprovider\x12 \n" +
	"\vproviderUid\x18\a \x01(\tR\vproviderUid\"1\n" +
	"\x15GetUserProfileRequest\x12\x18\n" +
	"\auserUid\x18\x01 \x01(\x05R\auserUid\"B\n" +
	"\x16GetUserProfileResponse\x12(\n" +
	"\buserInfo\x18\x01 \x01(\v2\f.UserProfileR\buserInfo\"<\n" +
	"\x10UserInfoResponse\x12(\n" +
	"\buserInfo\x18\x01 \x01(\v2\f.UserProfileR\buserInfo2\xaa\x02\n" +
	"\fUsersService\x12a\n" +
	"\rLoginFirebase\x12\x15.LoginFirebaseRequest\x1a\x16.LoginFirebaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/login/firebase\x12b\n" +
	"\x0eGetUserProfile\x12\x16.GetUserProfileRequest\x1a\x17.GetUserProfileResponse\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/v1/user/profile\x12S\n" +
	"\bUserInfo\x12\x16.google.protobuf.Empty\x1a\x11.UserInfoResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/user/infoB-Z+shortvid-backend/api/shortvid-service/v1;v1b\x06proto3"

var (
	file_shortvid_service_v1_user_proto_rawDescOnce sync.Once
	file_shortvid_service_v1_user_proto_rawDescData []byte
)

func file_shortvid_service_v1_user_proto_rawDescGZIP() []byte {
	file_shortvid_service_v1_user_proto_rawDescOnce.Do(func() {
		file_shortvid_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_user_proto_rawDesc), len(file_shortvid_service_v1_user_proto_rawDesc)))
	})
	return file_shortvid_service_v1_user_proto_rawDescData
}

var file_shortvid_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shortvid_service_v1_user_proto_goTypes = []any{
	(*LoginFirebaseRequest)(nil),   // 0: LoginFirebaseRequest
	(*LoginFirebaseResponse)(nil),  // 1: LoginFirebaseResponse
	(*UserProfile)(nil),            // 2: UserProfile
	(*GetUserProfileRequest)(nil),  // 3: GetUserProfileRequest
	(*GetUserProfileResponse)(nil), // 4: GetUserProfileResponse
	(*UserInfoResponse)(nil),       // 5: UserInfoResponse
	(*emptypb.Empty)(nil),          // 6: google.protobuf.Empty
}
var file_shortvid_service_v1_user_proto_depIdxs = []int32{
	2, // 0: LoginFirebaseResponse.user:type_name -> UserProfile
	2, // 1: GetUserProfileResponse.userInfo:type_name -> UserProfile
	2, // 2: UserInfoResponse.userInfo:type_name -> UserProfile
	0, // 3: UsersService.LoginFirebase:input_type -> LoginFirebaseRequest
	3, // 4: UsersService.GetUserProfile:input_type -> GetUserProfileRequest
	6, // 5: UsersService.UserInfo:input_type -> google.protobuf.Empty
	1, // 6: UsersService.LoginFirebase:output_type -> LoginFirebaseResponse
	4, // 7: UsersService.GetUserProfile:output_type -> GetUserProfileResponse
	5, // 8: UsersService.UserInfo:output_type -> UserInfoResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shortvid_service_v1_user_proto_init() }
func file_shortvid_service_v1_user_proto_init() {
	if File_shortvid_service_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_user_proto_rawDesc), len(file_shortvid_service_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortvid_service_v1_user_proto_goTypes,
		DependencyIndexes: file_shortvid_service_v1_user_proto_depIdxs,
		MessageInfos:      file_shortvid_service_v1_user_proto_msgTypes,
	}.Build()
	File_shortvid_service_v1_user_proto = out.File
	file_shortvid_service_v1_user_proto_goTypes = nil
	file_shortvid_service_v1_user_proto_depIdxs = nil
}
