// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             v6.33.2
// source: shortvid-service/v1/user.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationUsersServiceGetUserProfile = "/UsersService/GetUserProfile"
const OperationUsersServiceLoginFirebase = "/UsersService/LoginFirebase"
const OperationUsersServiceUserInfo = "/UsersService/UserInfo"

type UsersServiceHTTPServer interface {
	// GetUserProfile 通过userUid获取用户信息
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	// LoginFirebase firebase登录
	LoginFirebase(context.Context, *LoginFirebaseRequest) (*LoginFirebaseResponse, error)
	// UserInfo 获取自己的用户信息
	UserInfo(context.Context, *emptypb.Empty) (*UserInfoResponse, error)
}

func RegisterUsersServiceHTTPServer(s *http.Server, srv UsersServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/api/v1/login/firebase", _UsersService_LoginFirebase0_HTTP_Handler(srv))
	r.POST("/api/v1/user/profile", _UsersService_GetUserProfile0_HTTP_Handler(srv))
	r.POST("/api/v1/user/info", _UsersService_UserInfo0_HTTP_Handler(srv))
}

func _UsersService_LoginFirebase0_HTTP_Handler(srv UsersServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in LoginFirebaseRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersServiceLoginFirebase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginFirebase(ctx, req.(*LoginFirebaseRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*LoginFirebaseResponse)
		return ctx.Result(200, reply)
	}
}

func _UsersService_GetUserProfile0_HTTP_Handler(srv UsersServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersServiceGetUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserProfile(ctx, req.(*GetUserProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _UsersService_UserInfo0_HTTP_Handler(srv UsersServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUsersServiceUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserInfo(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserInfoResponse)
		return ctx.Result(200, reply)
	}
}

type UsersServiceHTTPClient interface {
	// GetUserProfile 通过userUid获取用户信息
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest, opts ...http.CallOption) (rsp *GetUserProfileResponse, err error)
	// LoginFirebase firebase登录
	LoginFirebase(ctx context.Context, req *LoginFirebaseRequest, opts ...http.CallOption) (rsp *LoginFirebaseResponse, err error)
	// UserInfo 获取自己的用户信息
	UserInfo(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *UserInfoResponse, err error)
}

type UsersServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUsersServiceHTTPClient(client *http.Client) UsersServiceHTTPClient {
	return &UsersServiceHTTPClientImpl{client}
}

// GetUserProfile 通过userUid获取用户信息
func (c *UsersServiceHTTPClientImpl) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...http.CallOption) (*GetUserProfileResponse, error) {
	var out GetUserProfileResponse
	pattern := "/api/v1/user/profile"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersServiceGetUserProfile))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginFirebase firebase登录
func (c *UsersServiceHTTPClientImpl) LoginFirebase(ctx context.Context, in *LoginFirebaseRequest, opts ...http.CallOption) (*LoginFirebaseResponse, error) {
	var out LoginFirebaseResponse
	pattern := "/api/v1/login/firebase"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersServiceLoginFirebase))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UserInfo 获取自己的用户信息
func (c *UsersServiceHTTPClientImpl) UserInfo(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*UserInfoResponse, error) {
	var out UserInfoResponse
	pattern := "/api/v1/user/info"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationUsersServiceUserInfo))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
