// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shortvid-service/v1/users.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginFirebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=idToken,proto3" json:"idToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseRequest) Reset() {
	*x = LoginFirebaseRequest{}
	mi := &file_shortvid_service_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseRequest) ProtoMessage() {}

func (x *LoginFirebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseRequest.ProtoReflect.Descriptor instead.
func (*LoginFirebaseRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *LoginFirebaseRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type LoginFirebaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseResponse) Reset() {
	*x = LoginFirebaseResponse{}
	mi := &file_shortvid_service_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseResponse) ProtoMessage() {}

func (x *LoginFirebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseResponse.ProtoReflect.Descriptor instead.
func (*LoginFirebaseResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_users_proto_rawDescGZIP(), []int{1}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_shortvid_service_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUid   string                 `protobuf:"bytes,5,opt,name=provider_uid,json=providerUid,proto3" json:"provider_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_shortvid_service_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserResponse) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *GetUserResponse) GetProviderUid() string {
	if x != nil {
		return x.ProviderUid
	}
	return ""
}

var File_shortvid_service_v1_users_proto protoreflect.FileDescriptor

const file_shortvid_service_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x1fshortvid-service/v1/users.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x14LoginFirebaseRequest\x12\x18\n" +
	"\aidToken\x18\x01 \x01(\tR\aidToken\"\x17\n" +
	"\x15LoginFirebaseResponse\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x9a\x01\n" +
	"\x0fGetUserResponse\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_uid\x18\x05 \x01(\tR\vproviderUid2\xbb\x01\n" +
	"\fUsersService\x12a\n" +
	"\rLoginFirebase\x12\x15.LoginFirebaseRequest\x1a\x16.LoginFirebaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/login/firebase\x12H\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/users/{id}B-Z+shortvid-backend/api/shortvid-service/v1;v1b\x06proto3"

var (
	file_shortvid_service_v1_users_proto_rawDescOnce sync.Once
	file_shortvid_service_v1_users_proto_rawDescData []byte
)

func file_shortvid_service_v1_users_proto_rawDescGZIP() []byte {
	file_shortvid_service_v1_users_proto_rawDescOnce.Do(func() {
		file_shortvid_service_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_users_proto_rawDesc), len(file_shortvid_service_v1_users_proto_rawDesc)))
	})
	return file_shortvid_service_v1_users_proto_rawDescData
}

var file_shortvid_service_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shortvid_service_v1_users_proto_goTypes = []any{
	(*LoginFirebaseRequest)(nil),  // 0: LoginFirebaseRequest
	(*LoginFirebaseResponse)(nil), // 1: LoginFirebaseResponse
	(*GetUserRequest)(nil),        // 2: GetUserRequest
	(*GetUserResponse)(nil),       // 3: GetUserResponse
}
var file_shortvid_service_v1_users_proto_depIdxs = []int32{
	0, // 0: UsersService.LoginFirebase:input_type -> LoginFirebaseRequest
	2, // 1: UsersService.GetUser:input_type -> GetUserRequest
	1, // 2: UsersService.LoginFirebase:output_type -> LoginFirebaseResponse
	3, // 3: UsersService.GetUser:output_type -> GetUserResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shortvid_service_v1_users_proto_init() }
func file_shortvid_service_v1_users_proto_init() {
	if File_shortvid_service_v1_users_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_users_proto_rawDesc), len(file_shortvid_service_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortvid_service_v1_users_proto_goTypes,
		DependencyIndexes: file_shortvid_service_v1_users_proto_depIdxs,
		MessageInfos:      file_shortvid_service_v1_users_proto_msgTypes,
	}.Build()
	File_shortvid_service_v1_users_proto = out.File
	file_shortvid_service_v1_users_proto_goTypes = nil
	file_shortvid_service_v1_users_proto_depIdxs = nil
}
