// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: shortvid-service/v1/user.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginFirebaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdToken       string                 `protobuf:"bytes,1,opt,name=idToken,proto3" json:"idToken,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseRequest) Reset() {
	*x = LoginFirebaseRequest{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseRequest) ProtoMessage() {}

func (x *LoginFirebaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseRequest.ProtoReflect.Descriptor instead.
func (*LoginFirebaseRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{0}
}

func (x *LoginFirebaseRequest) GetIdToken() string {
	if x != nil {
		return x.IdToken
	}
	return ""
}

type LoginFirebaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"`
	User          *UserProfile           `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFirebaseResponse) Reset() {
	*x = LoginFirebaseResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFirebaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFirebaseResponse) ProtoMessage() {}

func (x *LoginFirebaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFirebaseResponse.ProtoReflect.Descriptor instead.
func (*LoginFirebaseResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{1}
}

func (x *LoginFirebaseResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginFirebaseResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginFirebaseResponse) GetUser() *UserProfile {
	if x != nil {
		return x.User
	}
	return nil
}

type UserProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUid   string                 `protobuf:"bytes,5,opt,name=provider_uid,json=providerUid,proto3" json:"provider_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserProfile) Reset() {
	*x = UserProfile{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfile) ProtoMessage() {}

func (x *UserProfile) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfile.ProtoReflect.Descriptor instead.
func (*UserProfile) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserProfile) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserProfile) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserProfile) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UserProfile) GetProviderUid() string {
	if x != nil {
		return x.ProviderUid
	}
	return ""
}

type UserDTO struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderUid   string                 `protobuf:"bytes,6,opt,name=provider_uid,json=providerUid,proto3" json:"provider_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDTO) Reset() {
	*x = UserDTO{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDTO) ProtoMessage() {}

func (x *UserDTO) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDTO.ProtoReflect.Descriptor instead.
func (*UserDTO) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{3}
}

func (x *UserDTO) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserDTO) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserDTO) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserDTO) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserDTO) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *UserDTO) GetProviderUid() string {
	if x != nil {
		return x.ProviderUid
	}
	return ""
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserDTO               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserResponse) GetUser() *UserDTO {
	if x != nil {
		return x.User
	}
	return nil
}

type GetMyUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyUserRequest) Reset() {
	*x = GetMyUserRequest{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUserRequest) ProtoMessage() {}

func (x *GetMyUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUserRequest.ProtoReflect.Descriptor instead.
func (*GetMyUserRequest) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{6}
}

type GetMyUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserDTO               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMyUserResponse) Reset() {
	*x = GetMyUserResponse{}
	mi := &file_shortvid_service_v1_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMyUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMyUserResponse) ProtoMessage() {}

func (x *GetMyUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shortvid_service_v1_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMyUserResponse.ProtoReflect.Descriptor instead.
func (*GetMyUserResponse) Descriptor() ([]byte, []int) {
	return file_shortvid_service_v1_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetMyUserResponse) GetUser() *UserDTO {
	if x != nil {
		return x.User
	}
	return nil
}

var File_shortvid_service_v1_user_proto protoreflect.FileDescriptor

const file_shortvid_service_v1_user_proto_rawDesc = "" +
	"\n" +
	"\x1eshortvid-service/v1/user.proto\x1a\x1cgoogle/api/annotations.proto\"0\n" +
	"\x14LoginFirebaseRequest\x12\x18\n" +
	"\aidToken\x18\x01 \x01(\tR\aidToken\"\x7f\n" +
	"\x15LoginFirebaseResponse\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\x12 \n" +
	"\x04user\x18\x03 \x01(\v2\f.UserProfileR\x04user\"\x96\x01\n" +
	"\vUserProfile\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x04 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_uid\x18\x05 \x01(\tR\vproviderUid\"\xa2\x01\n" +
	"\aUserDTO\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_uid\x18\x06 \x01(\tR\vproviderUid\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"/\n" +
	"\x0fGetUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.UserDTOR\x04user\"\x12\n" +
	"\x10GetMyUserRequest\"1\n" +
	"\x11GetMyUserResponse\x12\x1c\n" +
	"\x04user\x18\x01 \x01(\v2\b.UserDTOR\x04user2\x88\x02\n" +
	"\fUsersService\x12a\n" +
	"\rLoginFirebase\x12\x15.LoginFirebaseRequest\x1a\x16.LoginFirebaseResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/api/v1/login/firebase\x12E\n" +
	"\aGetUser\x12\x0f.GetUserRequest\x1a\x10.GetUserResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/api/v1/user\x12N\n" +
	"\tGetMyUser\x12\x11.GetMyUserRequest\x1a\x12.GetMyUserResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/api/v1/user/meB-Z+shortvid-backend/api/shortvid-service/v1;v1b\x06proto3"

var (
	file_shortvid_service_v1_user_proto_rawDescOnce sync.Once
	file_shortvid_service_v1_user_proto_rawDescData []byte
)

func file_shortvid_service_v1_user_proto_rawDescGZIP() []byte {
	file_shortvid_service_v1_user_proto_rawDescOnce.Do(func() {
		file_shortvid_service_v1_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_user_proto_rawDesc), len(file_shortvid_service_v1_user_proto_rawDesc)))
	})
	return file_shortvid_service_v1_user_proto_rawDescData
}

var file_shortvid_service_v1_user_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_shortvid_service_v1_user_proto_goTypes = []any{
	(*LoginFirebaseRequest)(nil),  // 0: LoginFirebaseRequest
	(*LoginFirebaseResponse)(nil), // 1: LoginFirebaseResponse
	(*UserProfile)(nil),           // 2: UserProfile
	(*UserDTO)(nil),               // 3: UserDTO
	(*GetUserRequest)(nil),        // 4: GetUserRequest
	(*GetUserResponse)(nil),       // 5: GetUserResponse
	(*GetMyUserRequest)(nil),      // 6: GetMyUserRequest
	(*GetMyUserResponse)(nil),     // 7: GetMyUserResponse
}
var file_shortvid_service_v1_user_proto_depIdxs = []int32{
	2, // 0: LoginFirebaseResponse.user:type_name -> UserProfile
	3, // 1: GetUserResponse.user:type_name -> UserDTO
	3, // 2: GetMyUserResponse.user:type_name -> UserDTO
	0, // 3: UsersService.LoginFirebase:input_type -> LoginFirebaseRequest
	4, // 4: UsersService.GetUser:input_type -> GetUserRequest
	6, // 5: UsersService.GetMyUser:input_type -> GetMyUserRequest
	1, // 6: UsersService.LoginFirebase:output_type -> LoginFirebaseResponse
	5, // 7: UsersService.GetUser:output_type -> GetUserResponse
	7, // 8: UsersService.GetMyUser:output_type -> GetMyUserResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_shortvid_service_v1_user_proto_init() }
func file_shortvid_service_v1_user_proto_init() {
	if File_shortvid_service_v1_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shortvid_service_v1_user_proto_rawDesc), len(file_shortvid_service_v1_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shortvid_service_v1_user_proto_goTypes,
		DependencyIndexes: file_shortvid_service_v1_user_proto_depIdxs,
		MessageInfos:      file_shortvid_service_v1_user_proto_msgTypes,
	}.Build()
	File_shortvid_service_v1_user_proto = out.File
	file_shortvid_service_v1_user_proto_goTypes = nil
	file_shortvid_service_v1_user_proto_depIdxs = nil
}
