apiVersion: v1
kind: Service
metadata:
  name: shortvid-service-svc
  namespace: default
spec:
  selector:
    app: shortvid-service # 和pod的label一致
  type: NodePort
  ports:
    - name: http
      port: 8000 # k8s集群内的端口
      targetPort: 8000 # 容器内的端口
      nodePort: 30080 # 对外暴露的端口
    - name: grpc
      port: 9000
      targetPort: 9000
      nodePort: 30090