// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"shortvid-backend/app/shortvid-service/internal/biz"
	"shortvid-backend/app/shortvid-service/internal/conf"
	"shortvid-backend/app/shortvid-service/internal/data"
	"shortvid-backend/app/shortvid-service/internal/data/infra/cache"
	"shortvid-backend/app/shortvid-service/internal/data/infra/db"
	"shortvid-backend/app/shortvid-service/internal/data/infra/storage"
	"shortvid-backend/app/shortvid-service/internal/server"
	"shortvid-backend/app/shortvid-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, firebase *conf.Firebase, jwt *conf.Jwt, session *conf.Session, minio *conf.Minio, logger log.Logger) (*kratos.App, func(), error) {
	gormDB := db.NewDB(confData)
	client := cache.NewRedis(confData)
	minioClient := storage.NewMinioClient(minio)
	dataData, cleanup, err := data.NewData(gormDB, client, minioClient, logger)
	if err != nil {
		return nil, nil, err
	}
	usersRepo := data.NewUsersRepo(dataData)
	usersUsecase := biz.NewUsersUsecase(logger, usersRepo)
	firebaseService, err := service.NewFirebaseService(logger, firebase)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwtService := service.NewJwtService(jwt, logger)
	userSessionRepo := data.NewUserSessionRepo(dataData)
	cacheService := service.NewCacheService(client, logger)
	userSessionService := service.NewUserSessionService(logger, session, userSessionRepo, cacheService, jwtService)
	usersService := service.NewUsersService(logger, usersUsecase, firebaseService, jwtService, userSessionService, cacheService)
	grpcServer := server.NewGRPCServer(confServer, usersService, logger)
	httpServer := server.NewHTTPServer(confServer, jwt, usersService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
