// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v3"
	"shortvid-backend/app/shortvid-service/internal/biz"
	"shortvid-backend/app/shortvid-service/internal/conf"
	"shortvid-backend/app/shortvid-service/internal/data"
	"shortvid-backend/app/shortvid-service/internal/data/infra/db"
	"shortvid-backend/app/shortvid-service/internal/data/infra/storage"
	"shortvid-backend/app/shortvid-service/internal/server"
	"shortvid-backend/app/shortvid-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, s3 *conf.S3) (*kratos.App, func(), error) {
	healthService := service.NewHealthService()
	gormDB := db.NewDB(confData)
	s3Data := storage.NewS3(s3)
	dataData, cleanup, err := data.NewData(gormDB, s3Data)
	if err != nil {
		return nil, nil, err
	}
	s3Repo := data.NewS3Repo(s3, dataData)
	s3Usecase := biz.NewS3Usecase(s3, s3Repo)
	uploadService := service.NewUploadService(s3Usecase)
	httpServer := server.NewHTTPServer(confServer, healthService, uploadService)
	app := newApp(httpServer)
	return app, func() {
		cleanup()
	}, nil
}
