server:
  http:
    addr: 0.0.0.0:8000
    timeout: 60s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 10s

data:
  mysql:
    dsn: root:123456@tcp(127.0.0.1:3306)/shortvid?parseTime=True&loc=UTC
    slow_sql_threshold: 0.2s # 慢查询阈值，单位秒
    max_open_conns: 100 # 最大打开连接数
    max_idle_conns: 10 # 最大空闲连接数

s3:
  endpoint: ENDPOINT
  bucket: BUCKET
  s3_access_key: S3_ACCESS_KEY
  s3_secret_key: S3_SECRET_KEY
  region: REGION
  use_path_style: false
  sts_access_key: STS_ACCESS_KEY
  sts_secret_key: STS_SECRET_KEY
  sts_role_arn: STS_ROLE_ARN
  sts_session_name: STS_SESSION_NAME
  sts_duration_seconds: 3600