// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v6.33.2
// source: v1/user/user.proto

package userV1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationUserServiceGetUserProfile = "/user.v1.UserService/GetUserProfile"
const OperationUserServiceLoginFirebase = "/user.v1.UserService/LoginFirebase"
const OperationUserServiceLoginGithub = "/user.v1.UserService/LoginGithub"
const OperationUserServiceUserInfo = "/user.v1.UserService/UserInfo"

type UserServiceHTTPServer interface {
	// GetUserProfile 通过uid获取用户信息
	GetUserProfile(context.Context, *GetUserProfileRequest) (*GetUserProfileResponse, error)
	// LoginFirebase firebase登录
	LoginFirebase(context.Context, *FirebaseLoginRequest) (*FirebaseLoginResponse, error)
	// LoginGithub github登录
	LoginGithub(context.Context, *GithubLoginRequest) (*GithubLoginResponse, error)
	// UserInfo 获取自己的用户信息
	UserInfo(context.Context, *emptypb.Empty) (*UserInfoResponse, error)
}

func RegisterUserServiceHTTPServer(s *http.Server, srv UserServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("POST", "/api/v1/firebase/login", _UserService_LoginFirebase0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/github/login", _UserService_LoginGithub0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/user/profile", _UserService_GetUserProfile0_HTTP_Handler(srv))
	r.Handle("POST", "/api/v1/user/info", _UserService_UserInfo0_HTTP_Handler(srv))
}

func _UserService_LoginFirebase0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in FirebaseLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceLoginFirebase)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginFirebase(ctx, req.(*FirebaseLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*FirebaseLoginResponse)
		return ctx.Result(200, reply)
	}
}

func _UserService_LoginGithub0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GithubLoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceLoginGithub)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.LoginGithub(ctx, req.(*GithubLoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GithubLoginResponse)
		return ctx.Result(200, reply)
	}
}

func _UserService_GetUserProfile0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetUserProfileRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceGetUserProfile)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetUserProfile(ctx, req.(*GetUserProfileRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetUserProfileResponse)
		return ctx.Result(200, reply)
	}
}

func _UserService_UserInfo0_HTTP_Handler(srv UserServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationUserServiceUserInfo)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UserInfo(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UserInfoResponse)
		return ctx.Result(200, reply)
	}
}

type UserServiceHTTPClient interface {
	// GetUserProfile 通过uid获取用户信息
	GetUserProfile(ctx context.Context, req *GetUserProfileRequest, opts ...http.CallOption) (rsp *GetUserProfileResponse, err error)
	// LoginFirebase firebase登录
	LoginFirebase(ctx context.Context, req *FirebaseLoginRequest, opts ...http.CallOption) (rsp *FirebaseLoginResponse, err error)
	// LoginGithub github登录
	LoginGithub(ctx context.Context, req *GithubLoginRequest, opts ...http.CallOption) (rsp *GithubLoginResponse, err error)
	// UserInfo 获取自己的用户信息
	UserInfo(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *UserInfoResponse, err error)
}

type UserServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewUserServiceHTTPClient(client *http.Client) UserServiceHTTPClient {
	return &UserServiceHTTPClientImpl{client}
}

// GetUserProfile 通过uid获取用户信息
func (c *UserServiceHTTPClientImpl) GetUserProfile(ctx context.Context, in *GetUserProfileRequest, opts ...http.CallOption) (*GetUserProfileResponse, error) {
	var out GetUserProfileResponse
	pattern := "/api/v1/user/profile"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceGetUserProfile),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginFirebase firebase登录
func (c *UserServiceHTTPClientImpl) LoginFirebase(ctx context.Context, in *FirebaseLoginRequest, opts ...http.CallOption) (*FirebaseLoginResponse, error) {
	var out FirebaseLoginResponse
	pattern := "/api/v1/firebase/login"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceLoginFirebase),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// LoginGithub github登录
func (c *UserServiceHTTPClientImpl) LoginGithub(ctx context.Context, in *GithubLoginRequest, opts ...http.CallOption) (*GithubLoginResponse, error) {
	var out GithubLoginResponse
	pattern := "/api/v1/github/login"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceLoginGithub),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UserInfo 获取自己的用户信息
func (c *UserServiceHTTPClientImpl) UserInfo(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*UserInfoResponse, error) {
	var out UserInfoResponse
	pattern := "/api/v1/user/info"
	path := http.BuildPath(pattern, in)
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.ContentType("application/protojson"),
		http.Operation(OperationUserServiceUserInfo),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
