// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v3.0.0
// - protoc             v6.33.2
// source: v1/health/health.proto

package healthV1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationHealthServiceHealth = "/health.v1.HealthService/Health"

type HealthServiceHTTPServer interface {
	Health(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/api/v1/health", _HealthService_Health0_HTTP_Handler(srv))
}

func _HealthService_Health0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in emptypb.Empty
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Health(ctx, req.(*emptypb.Empty))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*emptypb.Empty)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	Health(ctx context.Context, req *emptypb.Empty, opts ...http.CallOption) (rsp *emptypb.Empty, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

func (c *HealthServiceHTTPClientImpl) Health(ctx context.Context, in *emptypb.Empty, opts ...http.CallOption) (*emptypb.Empty, error) {
	var out emptypb.Empty
	pattern := "/api/v1/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationHealthServiceHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
