// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUserSession = "user_session"

// UserSession 用户会话表
type UserSession struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:主键" json:"id"`                        // 主键
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_at"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;comment:逻辑删除标记" json:"deleted_at"`                                  // 逻辑删除标记
	UserUID   int32          `gorm:"column:user_uid;not null;comment:用户id" json:"user_uid"`                               // 用户id
	SessionID string         `gorm:"column:session_id;not null;comment:会话id" json:"session_id"`                           // 会话id
	IP        string         `gorm:"column:ip;not null;comment:ip" json:"ip"`                                             // ip
	UserAgent string         `gorm:"column:user_agent;not null;comment:用户代理" json:"user_agent"`                           // 用户代理
	Platform  string         `gorm:"column:platform;not null;comment:平台" json:"platform"`                                 // 平台
	ExpiresAt time.Time      `gorm:"column:expires_at;not null;default:CURRENT_TIMESTAMP;comment:过期时间" json:"expires_at"` // 过期时间
}

// TableName UserSession's table name
func (*UserSession) TableName() string {
	return TableNameUserSession
}
