name: Deploy Shortvid Service

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Render Manifest
        env:
          IMAGE_NAME: docker.cnb.cool/${{ secrets.CNB_REPO_SLUG }}/shortvid-service
          IMAGE_TAG: ${{ github.ref_name }}
        run: |
          echo "IMAGE_NAME: $IMAGE_NAME"
          echo "IMAGE_TAG: $IMAGE_TAG"
          envsubst < k8s/shortvid-service/deployment.yaml > deployment.yaml

      - name: Deploy
        run: |
          kubectl apply -f deployment.yaml
